import type { Service } from "@/types/service.types";

export const services: Service[] = [
  {
    name: "Manikűr",
    type: "top-level",
    price: null,
    duration: null,
    // image: "/photos/manicure.jpg",
    optionCount: 1,
  },
  {
    name: "Műkörömépítés",
    type: "top-level",
    price: null,
    duration: null,
    optionCount: 3,
  },
  {
    name: "Géllakk",
    type: "top-level",
    price: 7000,
    duration: 60,
    optionCount: 2,
  },
  {
    name: "Férfi Manikűr",
    type: "type",
    price: 4000,
    duration: 30,
  },
  {
    name: "Női Manikűr",
    type: "type",
    price: 4000,
    duration: 30,
  },
  {
    name: "Japán Manikűr",
    type: "type",
    price: 5500,
    duration: 45,
  },
  {
    name: "S Méret",
    type: "size",
    price: 8000,
    duration: 90,
  },
  {
    name: "S/M Méret",
    type: "size",
    price: 8500,
    duration: 90,
  },
  {
    name: "M Méret",
    type: "size",
    price: 9000,
    duration: 90,
  },
  {
    name: "M/L Méret",
    type: "size",
    price: 9500,
    duration: 120,
  },
  {
    name: "L Méret",
    type: "size",
    price: 10000,
    duration: 120,
  },
  {
    name: "XL Méret",
    type: "size",
    price: 11000,
    duration: 150,
  },
  {
    name: "Beépített Francia",
    type: "decoration",
    price: 2500,
    duration: 40,
  },
  {
    name: "Francia Festés",
    type: "decoration",
    price: 1000,
    duration: 20,
  },
  {
    name: "Babyboomer",
    type: "decoration",
    price: 1000,
    duration: 10,
  },
  {
    name: "Kis Díszítés",
    type: "decoration",
    price: 1000,
    duration: 15,
  },
  {
    name: "Közepes Díszítés",
    type: "decoration",
    price: 1500,
    duration: 25,
  },
  {
    name: "Nagy Díszítés",
    type: "decoration",
    price: 2500,
    duration: 35,
  },
  {
    name: "Nem kérek extra díszítést",
    type: "decoration",
    price: 0,
    duration: 0,
  },
  {
    name: "Van Más Munkája a Körmömön",
    type: "extra",
    price: 3000,
    duration: 30,
  },
  {
    name: "Nincs Más Munkája a Körmömön",
    type: "extra",
    price: 0,
    duration: 0,
  },
];
